### ISSUE TITLE
bootstrap.sh build issue #2

### ISSUE THREAD

**Issue by ArcadeDan** [Agnes-os/Agnes-os#2]
Debian GNU/Linux 10 (buster) on Windows 10 x86_64  (WSL2)
Issue :  running bootstrap.sh regardless if csh and ksh are present will loop and output the text below

NOTE: default prefix=/usr/local 
/mnt/c/Users/Daniel/Documents/code/C/agnes-os/vendor/bmake/boot-strap --prefix=/mnt/c/Users/Daniel/Documents/code/C/agnes-os/.build/usr -o . op=test
NOTE: default prefix=/usr/local 
/mnt/c/Users/Daniel/Documents/code/C/agnes-os/vendor/bmake/boot-strap --prefix=/mnt/c/Users/Daniel/Documents/code/C/agnes-os/.build/usr -o . op=test
NOTE: default prefix=/usr/local 
/mnt/c/Users/Daniel/Documents/code/C/agnes-os/vendor/bmake/boot-strap --prefix=/mnt/c/Users/Daniel/Documents/code/C/agnes-os/.build/usr -o . op=test
NOTE: default prefix=/usr/local 
/mnt/c/Users/Daniel/Documents/code/C/agnes-os/vendor/bmake/boot-strap --prefix=/mnt/c/Users/Daniel/Documents/code/C/agnes-os/.build/usr -o . op=test
NOTE: default prefix=/usr/local 
/mnt/c/Users/Daniel/Documents/code/C/agnes-os/vendor/bmake/boot-strap --prefix=/mnt/c/Users/Daniel/Documents/code/C/agnes-os/.build/usr -o . op=test
NOTE: default prefix=/usr/local

**Comment by hodbogi** [comment]
I am looking into the possibility of using cmake for the build system.  This should help with portability.

**Comment by hodbogi** [comment]
This issue has been resolved by replacement of the build system with cmake.
